name: Deploy

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

permissions:
    contents: write

jobs:
    ManyLinux_x86_64:
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/build_package_for_manylinux@master

    macos_x86_64:
        runs-on: macos-latest
        steps:
          - uses: maxim-lobanov/setup-xcode@v1
            with:
                xcode-version: '15.3'
          - uses: MartinPdeS/MPSActions/build_package_for_MacOS@master


    Windows_x86_64:
        runs-on: windows-latest
        steps:
          - uses: MartinPdeS/MPSActions/build_package_for_Windows@master


    publish_coverage:
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        needs: [ManyLinux_x86_64]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_coverage@master
            with:
                package-name: LightWave2D
                python-version: "3.11"
                auth: ${{ secrets.GIST_TOKEN }}
                gistID: ec3ae9cb78858c919205d85b8bf67e6b

    publish_documentation:
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        needs: [ManyLinux_x86_64]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_documentation@master
            with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                package-name: LightWave2D
                python-version: "3.11" #no documentation for python 3.7 (pickle5 not presentË˜)

    publish_wheel:
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        needs: [ManyLinux_x86_64, macos_x86_64, Windows_x86_64, publish_documentation, publish_coverage]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_pypi@master
            with:
                python-version: "3.11"
                password: ${{ secrets.PYPI_API_TOKEN }}

# -
