# Simple workflow for deploying static content to GitHub Pages
name: Deploy coverage

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]


# Sets permissions of the GITHUB_TOKEN to persist coverage-comment data.
permissions:
  contents: write

jobs:
  ManyLinux_x86_64:
    uses: MartinPdeS/MPSActions/.github/workflows/publish_coverage.yml@v2
    with:
      python-version: "3.11"
      apt-package: xvfb
      coverage-package: LightWave2D
    secrets:
      _GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
