name: Deploy

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

permissions:
    contents: write

jobs:
    build_pure_python:
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/build_pure_python_package@master
            with:
                python-version: '3.11'


    publish_coverage:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [ManyLinux_x86_64]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_coverage@master
            with:
                package-name: LightWave2D
                python-version: "3.11"
                auth: ${{ secrets.GIST_TOKEN }}
                gistID: f0955be398d59efac69042c1b0fbece2


    publish_documentation:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [ManyLinux_x86_64]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_documentation@master
            with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                package-name: LightWave2D
                python-version: "3.11" #no documentation for python 3.7 (pickle5 not presentË˜)


    publish_wheel:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [Windows_x86_64, ManyLinux_x86_64, macos_x86_64, publish_documentation, publish_coverage]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_pypi@master
            with:
                python-version: "3.11"
                password: ${{ secrets.PYPI_API_TOKEN }}

# -
